defaults: &defaults
  docker:
    - image: 'circleci/node:13'
  working_directory: ~/project/build-your-own-mint

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install && npm run decrypt
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - build-your-own-mint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run get
  typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run typecheck
workflows:
  version: 2
  test:
    jobs:
      - install
      - typecheck:
          requires:
            - install
      - build:
          requires:
            - install
  nightly:
    triggers:
      - schedule:
          # 14 for 8am cst during DST, 13 otherwise.
          cron: '0 15 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - install
      - build:
          requires:
            - install
